name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        requireScope: false
        subjectPattern: ^(?![A-Z]).+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          doesn't start with an uppercase character.

  check-size:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check PR size
      run: |
        FILES_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}..HEAD | wc -l)
        LINES_CHANGED=$(git diff origin/${{ github.base_ref }}..HEAD --shortstat | awk '{print $4 + $6}')
        
        echo "Files changed: $FILES_CHANGED"
        echo "Lines changed: $LINES_CHANGED"
        
        if [ $LINES_CHANGED -gt 1000 ]; then
          echo "::warning::This PR changes $LINES_CHANGED lines. Consider breaking it into smaller PRs."
        fi
        
        echo "## PR Size" >> $GITHUB_STEP_SUMMARY
        echo "- Files changed: $FILES_CHANGED" >> $GITHUB_STEP_SUMMARY
        echo "- Lines changed: $LINES_CHANGED" >> $GITHUB_STEP_SUMMARY

  test-coverage-diff:
    runs-on: macos-latest
    
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Upload coverage for comparison
      uses: actions/upload-artifact@v4
      with:
        name: pr-coverage
        path: coverage/coverage-summary.json
        retention-days: 1

  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run security audit
      run: npm audit --production
      continue-on-error: true
    
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --only-verified